sudo: required
services:
  - docker
before_install:
  - docker build -t bkhbea/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bkhbea/react-test npm test -- --coverage

after_success:
  - docker build -t bkhbea/multi-client ./client
  - docker build -t bkhbea/multi-nginx ./nginx
  - docker build -t bkhbea/multi-server ./server
  - docker build -t bkhbea/multi-worker ./worker


 # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


 # push those images and push them to docker hub
  - docker push bkhbea/multi-client
  - docker push bkhbea/multi-nginx
  - docker push bkhbea/multi-server
  - docker push bkhbea/multi-worker


deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: MyMultiContainerApp
  env: Mymulticontainerapp-env
  bucket_name: elasticbeanstalk-ca-central-1-785213703975
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secrure:$AWS_SECRET_KEY